import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../styles/globals.css';
import SideNav from '@/components/sideNav';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'New Age',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SideNav />
        <main style={{ marginLeft: '240px', padding: '16px' }}>{children}</main>
      </body>
    </html>
  );
}
